/**
 * Centralized legal disclaimers (cahier des charges §34).
 *
 * ClaimCare AI is NOT a law firm and does NOT provide legal advice.
 * These texts must be surfaced on every important page/action.
 * Keep wording in sync with the Terms / Privacy / Disclaimer pages.
 */

export const PRIMARY_DISCLAIMER =
  "ClaimCare AI provides informational assistance only and does not provide legal advice. You remain responsible for reviewing and sending any document generated by the platform. For legal advice, consult a licensed attorney.";

export type DisclaimerKey =
  | "primary"
  | "signup"
  | "letter"
  | "complaint"
  | "health"
  | "expertReview";

export const DISCLAIMERS: Record<DisclaimerKey, string> = {
  primary: PRIMARY_DISCLAIMER,
  signup:
    "ClaimCare AI provides informational assistance only and does not provide legal, financial, medical, or insurance advice. You are responsible for reviewing all generated documents before using them.",
  letter:
    "This document is AI-generated for informational purposes. Review it carefully before sending it. For legal advice, consult a licensed attorney.",
  complaint:
    "Regulatory complaint procedures vary by state. Verify all information with your state Department of Insurance before filing.",
  health:
    "ClaimCare AI does not provide medical advice. For medical questions, consult a licensed healthcare professional.",
  expertReview:
    "Expert review is not legal advice unless provided by a licensed attorney under a separate agreement.",
};

/** Consent types recorded in the `user_consents` table at signup. */
export const CONSENT_TYPES = {
  terms: "terms_of_service",
  privacy: "privacy_policy",
  disclaimer: "legal_disclaimer",
  documentProcessing: "sensitive_document_processing",
} as const;
