import type { Case } from "@/lib/claimguard/types";

/**
 * Demo cases shown when Supabase is not configured, so the whole ClaimGuard
 * flow stays fully clickable in placeholder mode (no keys required).
 * These are illustrative only and never persisted.
 */
const NOW = "2026-08-23T09:00:00.000Z";

export const DEMO_CASES: Case[] = [
  {
    id: "demo-1",
    user_id: "demo",
    case_reference: "CG-2026-000042",
    organization_id: null,
    debtor_name: "Studio Nova SAS",
    debtor_email: "compta@studionova.fr",
    debtor_accounting_email: "compta@studionova.fr",
    debtor_contact_name: "Service comptabilité",
    debtor_contact_email: null,
    invoice_number: "F-2026-0117",
    invoice_date: "2026-06-15",
    due_date: "2026-07-15",
    amount_ht: 2500,
    vat_amount: 500,
    original_amount: 3000,
    remaining_amount: 3000,
    currency: "EUR",
    service_description: "Refonte du site vitrine — mission de 12 jours",
    payee_name: "Camille Freelance",
    iban: "FR76••••••••••••1234",
    bic: null,
    status: "waiting_for_organization",
    risk_level: "medium",
    completeness_score: 92,
    promised_payment_date: null,
    last_contact_at: "2026-08-18T09:00:00.000Z",
    next_action_at: "2026-08-25T09:00:00.000Z",
    automation_enabled: true,
    human_review_required: false,
    reminder_count: 1,
    ai_summary:
      "Facture de 3 000 € TTC échue depuis le 15/07. Premier contact envoyé, une relance effectuée. En attente de retour de la comptabilité.",
    ai_analysis: null,
    client_history: null,
    created_at: "2026-08-10T09:00:00.000Z",
    updated_at: NOW,
  },
  {
    id: "demo-2",
    user_id: "demo",
    case_reference: "CG-2026-000039",
    organization_id: null,
    debtor_name: "Agence Lumen",
    debtor_email: "finance@agencelumen.fr",
    debtor_accounting_email: null,
    debtor_contact_name: null,
    debtor_contact_email: null,
    invoice_number: "2026-88",
    invoice_date: "2026-07-01",
    due_date: "2026-07-31",
    amount_ht: 1400,
    vat_amount: 280,
    original_amount: 1680,
    remaining_amount: 0,
    currency: "EUR",
    service_description: "Rédaction de 8 articles de blog SEO",
    payee_name: "Camille Freelance",
    iban: "FR76••••••••••••1234",
    bic: null,
    status: "paid",
    risk_level: "low",
    completeness_score: 100,
    promised_payment_date: "2026-08-05",
    last_contact_at: "2026-08-04T09:00:00.000Z",
    next_action_at: null,
    automation_enabled: true,
    human_review_required: false,
    reminder_count: 0,
    ai_summary: "Réglée le 05/08 comme promis. Dossier prêt à être clôturé.",
    ai_analysis: null,
    client_history: null,
    created_at: "2026-07-20T09:00:00.000Z",
    updated_at: "2026-08-05T09:00:00.000Z",
  },
  {
    id: "demo-3",
    user_id: "demo",
    case_reference: "CG-2026-000051",
    organization_id: null,
    debtor_name: null,
    debtor_email: null,
    debtor_accounting_email: null,
    debtor_contact_name: null,
    debtor_contact_email: null,
    invoice_number: null,
    invoice_date: null,
    due_date: null,
    amount_ht: null,
    vat_amount: null,
    original_amount: null,
    remaining_amount: null,
    currency: "EUR",
    service_description: null,
    payee_name: null,
    iban: null,
    bic: null,
    status: "draft",
    risk_level: "low",
    completeness_score: 20,
    promised_payment_date: null,
    last_contact_at: null,
    next_action_at: null,
    automation_enabled: true,
    human_review_required: false,
    reminder_count: 0,
    ai_summary: null,
    ai_analysis: null,
    client_history: null,
    created_at: NOW,
    updated_at: NOW,
  },
];
