import type { Metadata } from "next";
import { DisclaimerBanner } from "@/components/disclaimer-banner";

export const metadata: Metadata = { title: "Disclaimer" };

export default function DisclaimerPage() {
  return (
    <article className="space-y-5">
      <h1 className="text-3xl font-bold tracking-tight">Legal Disclaimer</h1>
      <p className="text-sm text-muted-foreground">
        Last updated: {new Date().getFullYear()}
      </p>

      <DisclaimerBanner variant="primary" />

      <section className="space-y-3 text-sm leading-relaxed text-foreground/90">
        <h2 className="pt-2 text-lg font-semibold text-foreground">
          Not a law firm
        </h2>
        <p>
          ClaimCare AI is not a law firm, is not a licensed insurance adjuster
          or broker, and does not provide legal, financial, medical, or
          insurance advice. Using ClaimCare AI does not create an
          attorney-client relationship.
        </p>

        <h2 className="pt-2 text-lg font-semibold text-foreground">
          Informational assistance only
        </h2>
        <p>
          ClaimCare AI provides informational, documentary, and administrative
          assistance to help you understand and organize your insurance claim.
          Any analysis, score, recommendation, or document generated by the
          platform is for informational purposes only.
        </p>

        <h2 className="pt-2 text-lg font-semibold text-foreground">
          Your responsibility
        </h2>
        <p>
          You remain solely responsible for reviewing, verifying, and deciding
          whether to send any document generated by the platform. ClaimCare AI
          does not guarantee any outcome. For legal advice, consult a licensed
          attorney. For medical questions, consult a licensed healthcare
          professional. For regulatory matters, verify all information with your
          state Department of Insurance.
        </p>

        <p className="rounded-lg border border-warning/40 bg-warning/10 p-3 text-foreground">
          This page is a template and should be reviewed by qualified legal
          counsel before launch.
        </p>
      </section>
    </article>
  );
}
