-- ============================================================================
-- ClaimCare AI — RAG retrieval (§35)
-- ============================================================================
-- Cosine-similarity search over knowledge_base_chunks embeddings (pgvector).
-- Embeddings are generated by the app (OpenAI text-embedding-3-small, 1536-d)
-- when an admin saves a knowledge base entry.
-- ============================================================================

-- Approximate-nearest-neighbour index for cosine distance.
create index if not exists knowledge_base_chunks_embedding_idx
  on public.knowledge_base_chunks
  using hnsw (embedding vector_cosine_ops);

-- Retrieve the most similar chunks to a query embedding, with optional
-- state / insurance-type filtering. Runs as the caller (RLS applies; the
-- read policies allow authenticated users to read knowledge content).
create or replace function public.match_knowledge_chunks(
  query_embedding vector(1536),
  match_count int default 5,
  filter_state text default null,
  filter_insurance_type insurance_type default null
)
returns table (
  id uuid,
  entry_id uuid,
  chunk_text text,
  title text,
  source_url text,
  similarity float
)
language sql
stable
as $$
  select
    c.id,
    c.entry_id,
    c.chunk_text,
    e.title,
    e.source_url,
    1 - (c.embedding <=> query_embedding) as similarity
  from public.knowledge_base_chunks c
  join public.knowledge_base_entries e on e.id = c.entry_id
  where c.embedding is not null
    and (filter_state is null or e.state is null or e.state = filter_state)
    and (
      filter_insurance_type is null
      or e.insurance_type is null
      or e.insurance_type = filter_insurance_type
    )
  order by c.embedding <=> query_embedding
  limit match_count;
$$;

grant execute on function public.match_knowledge_chunks to authenticated;
